image: markhobson/maven-chrome:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn compile
    - echo "Compile complete."
  artifacts:
    paths:
      - target/surefire-reports/
test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean test -DuserName=$USERNAME -Dpassword=$PASSWORD -Dsurefire.reports.directory=target/surefire-reports
    - echo "Finishing tests..."
  artifacts:
        paths:
          - target/surefire-reports/