image: markhobson/maven-chrome:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn compile
    - echo "Compile complete."

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean test -Dselenide.headless=true -DuserName=$USERNAME -Dpassword=$PASSWORD
    - echo "Finishing tests..."