image: markhobson/maven-chrome:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn compile
    - echo "Compile complete."
test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean test -DuserEmail=$USERNAME -Dpassword=$PASSWORD
    - echo "Finishing tests..."
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml